import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "surface-container": "#e5eeff",
        "surface-container-low": "#eff4ff",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "surface-variant": "#d3e4fe",
        surface: "#f8f9ff",
        "surface-tint": "#2d6197",
        "inverse-surface": "#213145",
        "inverse-on-surface": "#eaf1ff",
        "inverse-primary": "#a0c9ff",
        primary: "#00355f",
        "on-primary": "#ffffff",
        "primary-container": "#0f4c81",
        "on-primary-container": "#8ebdf9",
        "primary-fixed": "#d2e4ff",
        "primary-fixed-dim": "#a0c9ff",
        "on-primary-fixed": "#001c37",
        "on-primary-fixed-variant": "#07497d",
        secondary: "#006a61",
        "on-secondary": "#ffffff",
        "secondary-container": "#86f2e4",
        "on-secondary-container": "#006f66",
        "secondary-fixed": "#89f5e7",
        "secondary-fixed-dim": "#6bd8cb",
        "on-secondary-fixed": "#00201d",
        "on-secondary-fixed-variant": "#005049",
        tertiary: "#313436",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#474b4d",
        "on-tertiary-container": "#b8bbbc",
        "tertiary-fixed": "#e0e3e5",
        "tertiary-fixed-dim": "#c4c7c9",
        "on-tertiary-fixed": "#191c1e",
        "on-tertiary-fixed-variant": "#444749",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#f8f9ff",
        "on-background": "#0b1c30",
        "on-surface": "#0b1c30",
        "on-surface-variant": "#42474f",
        outline: "#727780",
        "outline-variant": "#c2c7d1",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "stack-xs": "0.25rem",
        "stack-sm": "0.5rem",
        "stack-md": "1rem",
        "stack-lg": "1.5rem",
        gutter: "1rem",
        margin: "2rem",
        "container-max-width": "1440px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        "mono-data": ["ui-monospace", "monospace"],
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "mono-data": ["14px", { lineHeight: "20px", fontWeight: "500" }],
      },
      maxWidth: {
        "container-max-width": "1440px",
      },
    },
  },
  plugins: [],
};

export default config;
